include "defines.asm"

include "res/music/asof.asm"
include "res/music/cutie.asm"
; include "res/music/db.asm"
; include "res/music/haunted.asm"
; include "res/music/hydroplane.asm"
; include "res/music/jazzberr.asm"
; include "res/music/josss.asm"
; include "res/music/journey.asm"
; include "res/music/keisari.asm"
; include "res/music/leafpile.asm"
; include "res/music/nerve.asm"
; include "res/music/opl3_journey_to_the_forgotten_star.asm"
; include "res/music/opl3thing.asm"
; include "res/music/orca.asm"
; include "res/music/restart.asm"
; include "res/music/sinstrat.asm"
; include "res/music/sxtnt.asm"
; include "res/music/test.asm"
; include "res/music/thumb.asm"
; include "res/music/trance.asm"
; include "res/music/trial.asm"
; include "res/music/try_again.asm"
; include "res/music/wtf.asm"
; include "res/music/zen.asm"
